set(DSCPP_ROOT_DIR ${CMAKE_CURRENT_SOURCE_DIR})

set(DSCPP_INCLUDE_DIR ${DSCPP_ROOT_DIR}/include)
set(DSCPP_LIBHPP_DIR ${DSCPP_ROOT_DIR}/lib-hpp)
set(DSCPP_LIBRARY_DIR ${DSCPP_ROOT_DIR}/library)
set(DSCPP_CMAKE_DIR ${DSCPP_ROOT_DIR}/cmake)
set(DSCPP_BUILD_DIR ${DSCPP_ROOT_DIR}/build)

include_directories(${DSCPP_INCLUDE_DIR})
include_directories(${DSCPP_LIBHPP_DIR})